spring.application.name=order-service
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Circuit Breaker Configuration
#feign.circuitbreaker.enabled=true
spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.instances.userService.register-health-indicator=true
#check recent 5 requests
resilience4j.circuitbreaker.instances.userService.sliding-window-size=2
#if 50% of the requests fail, open the circuit
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
#Wait 10 sec before retrying after circuit is opened
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=20s
